# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Node CI-CD

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.17]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
      
      - name: Docker Login
        run:
          docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}

      - name: Build Docker images
        run:
          docker build --platform amd64 --build-arg DEPENDENCY=build/dependency -t express-cicd .
      - name: set tag Docker images
        run:
          docker tag spring-cicd la1av1a/express-cicd:${GITHUB_SHA::7}
      - name: Push Docker images
        run:
          docker push la1av1a/express-cicd:${GITHUB_SHA::7}
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.AWS_URL }}
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            docker pull la1av1a/express-cicd:${GITHUB_SHA::7}
            docker tag la1av1a/express-cicd:${GITHUB_SHA::7} express-cicd
            docker stop server
            docker run -d --rm --name server -p 80:8080 express-cicd
            docker rmi la1av1a/express-cicd:${GITHUB_SHA::7}
